### ISSUE TITLE
Wasteful code

### ISSUE THREAD

**Issue by listguy** [gil6464/pre-course-2021-final-boilerplate#1]
Save buttons spawn infinitely.

**Steps to recreate:**
1. click edit button
2. click save button
3. repeat steps 1 & 2 on the same to do element

**Expected result:**
0 or 1 save buttons, can be hidden

**result**:
2 hidden save buttons.

Potentially can reach infinite hidden buttons who do nothing

**Comment by gil6464** [comment]
@listguy thank you for your attention, i fixed this issue with simply "remove" insted of hidden.
